apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pytorchcnn-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-02-25T17:33:30.131880',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "pytorchcnn"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0}
spec:
  entrypoint: pytorchcnn
  templates:
  - name: preprocesstextdata
    container:
      args: [--input_data, /tmp/inputs/input_data/data, --dataset_url, 'https://kubeflow-dataset.s3.us-east-2.amazonaws.com/ag_news_csv.tar.gz',
        --output_data, /tmp/outputs/output_data/data]
      command: [python, /component/entry_point.py]
      image: jagadeeshj/data_prep_step:25-02-2021-17-32-24.356692
    inputs:
      artifacts:
      - name: input_data
        path: /tmp/inputs/input_data/data
        raw: {data: ''}
    outputs:
      artifacts:
      - {name: preprocesstextdata-output_data, path: /tmp/outputs/output_data/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Prepare
          data for PyTorch training.\n", "implementation": {"container": {"args":
          ["--input_data", {"inputPath": "input_data"}, "--dataset_url", {"inputValue":
          "dataset_url"}, "--output_data", {"outputPath": "output_data"}], "command":
          ["python", "/component/entry_point.py"], "image": "jagadeeshj/data_prep_step:25-02-2021-17-32-24.356692"}},
          "inputs": [{"description": "The path to the input dataset", "name": "input_data",
          "type": "String"}, {"description": "The path to the dataset file", "name":
          "dataset_url", "type": "String"}], "name": "PreProcessTextData", "outputs":
          [{"description": "Output data location", "name": "output_data", "type":
          "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest": "f3b2ab070c5b66e3f52fd5031f569252ff0b61b7517d88c1a0b5aca020bdd0fd",
          "url": "data_prep_step/bert/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"dataset_url":
          "https://kubeflow-dataset.s3.us-east-2.amazonaws.com/ag_news_csv.tar.gz"}'}
  - name: pytorchcnn
    dag:
      tasks:
      - {name: preprocesstextdata, template: preprocesstextdata}
      - name: tensorboard-viz
        template: tensorboard-viz
        dependencies: [train-pytorch-bert]
        arguments:
          parameters:
          - {name: train-pytorch-bert-TensorboardS3Path, value: '{{tasks.train-pytorch-bert.outputs.parameters.train-pytorch-bert-TensorboardS3Path}}'}
      - name: train-pytorch-bert
        template: train-pytorch-bert
        dependencies: [preprocesstextdata]
        arguments:
          artifacts:
          - {name: preprocesstextdata-output_data, from: '{{tasks.preprocesstextdata.outputs.artifacts.preprocesstextdata-output_data}}'}
      - name: webapplication-viz
        template: webapplication-viz
        dependencies: [train-pytorch-bert]
        arguments:
          parameters:
          - {name: train-pytorch-bert-WebS3Path, value: '{{tasks.train-pytorch-bert.outputs.parameters.train-pytorch-bert-WebS3Path}}'}
  - name: tensorboard-viz
    container:
      args: [--board_path, '{{inputs.parameters.train-pytorch-bert-TensorboardS3Path}}',
        --outputs, /tmp/outputs/outputs/data]
      command: [python, /component/entrypoint.py]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef: {key: AWS_ACCESS_KEY_ID, name: aws-secret}
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef: {key: AWS_SECRET_ACCESS_KEY, name: aws-secret}
      image: jagadeeshj/visualization_step:25-02-2021-17-32-24.356692
    inputs:
      parameters:
      - {name: train-pytorch-bert-TensorboardS3Path}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
      - {name: mlpipeline-metrics, path: /mlpipeline-metrics.json}
      - {name: tensorboard-viz-outputs, path: /tmp/outputs/outputs/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Tensorboard
          Viz", "implementation": {"container": {"args": ["--board_path", {"inputValue":
          "board_path"}, "--outputs", {"outputPath": "outputs"}], "command": ["python",
          "/component/entrypoint.py"], "fileOutputs": {"MLPipeline Metrics": "/mlpipeline-metrics.json",
          "MLPipeline UI metadata": "/mlpipeline-ui-metadata.json"}, "image": "jagadeeshj/visualization_step:25-02-2021-17-32-24.356692"}},
          "inputs": [{"description": "Path of Tensorboard log", "name": "board_path",
          "type": "String"}], "name": "Tensorboard Viz", "outputs": [{"name": "MLPipeline
          UI metadata", "type": "UI metadata"}, {"name": "MLPipeline Metrics", "type":
          "Metrics"}, {"description": "Path for the output", "name": "outputs", "type":
          "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest": "b015a53834ab95505dd57230f7fe99b79f702f19e40d1d78c8557302fa1f4d2b",
          "url": "visualization_step/bert/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"board_path":
          "{{inputs.parameters.train-pytorch-bert-TensorboardS3Path}}"}'}
  - name: train-pytorch-bert
    container:
      args: [--train_glob, /tmp/inputs/TrainingData/data, --model_save_path, /tmp/outputs/ModelCheckpoint/data,
        --tensorboard_root, /tmp/outputs/TensorboardLogs/data, --max_epochs, '2',
        --num_samples, '150', --batch_size, '16', --num_workers, '2', --learning_rate,
        '0.001', --accelerator, '', --bucket_name, kubeflow-dataset, --folder_name,
        bertViz, --webapp_path, /tmp/outputs/WebLogs/data]
      command: [python, /component/entry_point.py]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef: {key: AWS_ACCESS_KEY_ID, name: aws-secret}
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef: {key: AWS_SECRET_ACCESS_KEY, name: aws-secret}
      image: jagadeeshj/training_step:25-02-2021-17-32-24.356692
      resources:
        limits: {cpu: '4', memory: 14Gi}
    inputs:
      artifacts:
      - {name: preprocesstextdata-output_data, path: /tmp/inputs/TrainingData/data}
    outputs:
      parameters:
      - name: train-pytorch-bert-TensorboardS3Path
        valueFrom: {path: /logdir.txt}
      - name: train-pytorch-bert-WebS3Path
        valueFrom: {path: /logdirweb.txt}
      artifacts:
      - {name: train-pytorch-bert-ModelCheckpoint, path: /tmp/outputs/ModelCheckpoint/data}
      - {name: train-pytorch-bert-TensorboardLogs, path: /tmp/outputs/TensorboardLogs/data}
      - {name: train-pytorch-bert-TensorboardS3Path, path: /logdir.txt}
      - {name: train-pytorch-bert-WebLogs, path: /tmp/outputs/WebLogs/data}
      - {name: train-pytorch-bert-WebS3Path, path: /logdirweb.txt}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Train
          PyTorch Bert", "implementation": {"container": {"args": ["--train_glob",
          {"inputPath": "TrainingData"}, "--model_save_path", {"outputPath": "ModelCheckpoint"},
          "--tensorboard_root", {"outputPath": "TensorboardLogs"}, "--max_epochs",
          {"inputValue": "MaxEpochs"}, "--num_samples", {"inputValue": "NumSamples"},
          "--batch_size", {"inputValue": "BatchSize"}, "--num_workers", {"inputValue":
          "NumWorkers"}, "--learning_rate", {"inputValue": "LearningRate"}, "--accelerator",
          {"inputValue": "Accelerator"}, "--bucket_name", {"inputValue": "BucketName"},
          "--folder_name", {"inputValue": "FolderName"}, "--webapp_path", {"outputPath":
          "WebLogs"}], "command": ["python", "/component/entry_point.py"], "fileOutputs":
          {"TensorboardS3Path": "/logdir.txt", "WebS3Path": "/logdirweb.txt"}, "image":
          "jagadeeshj/training_step:25-02-2021-17-32-24.356692"}}, "inputs": [{"description":
          "Path to the training data", "name": "TrainingData", "type": "String"},
          {"description": "Maximum number of epochs", "name": "MaxEpochs", "type":
          "Integer"}, {"description": "Maximum number of samples", "name": "NumSamples",
          "type": "Integer"}, {"description": "Batch size", "name": "BatchSize", "type":
          "Integer"}, {"description": "Number of workers", "name": "NumWorkers", "type":
          "Integer"}, {"description": "Learning rate", "name": "LearningRate", "type":
          "Float"}, {"description": "multi gpu training", "name": "Accelerator", "type":
          "String"}, {"description": "S3 bucket name", "name": "BucketName", "type":
          "String"}, {"description": "S3 folder", "name": "FolderName", "type": "String"}],
          "name": "train_pytorch_bert", "outputs": [{"description": "Path for the
          resulting model checkpoint", "name": "ModelCheckpoint", "type": "Directory"},
          {"description": "Path for the tensorboard logs", "name": "TensorboardLogs",
          "type": "String"}, {"description": "Path for the web logs", "name": "WebLogs",
          "type": "String"}, {"description": "Tensorboard S3 Path", "name": "TensorboardS3Path",
          "type": "String"}, {"description": "Web S3 Path", "name": "WebS3Path", "type":
          "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest": "d42f7e12cda8532110a6a93d91a0b375190ee5f38dd2a5771d2ddddb9c63b129",
          "url": "training_step/bert/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"Accelerator":
          "", "BatchSize": "16", "BucketName": "kubeflow-dataset", "FolderName": "bertViz",
          "LearningRate": "0.001", "MaxEpochs": "2", "NumSamples": "150", "NumWorkers":
          "2"}'}
  - name: webapplication-viz
    container:
      args: [--board_path, '{{inputs.parameters.train-pytorch-bert-WebS3Path}}', --outputs,
        /tmp/outputs/outputs/data]
      command: [python, /component/entrypoint.py]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef: {key: AWS_ACCESS_KEY_ID, name: aws-secret}
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef: {key: AWS_SECRET_ACCESS_KEY, name: aws-secret}
      image: jagadeeshj/visualize_html:25-02-2021-17-32-24.356692
    inputs:
      parameters:
      - {name: train-pytorch-bert-WebS3Path}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
      - {name: webapplication-viz-outputs, path: /tmp/outputs/outputs/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "WebApplication
          Viz", "implementation": {"container": {"args": ["--board_path", {"inputValue":
          "board_path"}, "--outputs", {"outputPath": "outputs"}], "command": ["python",
          "/component/entrypoint.py"], "fileOutputs": {"MLPipeline UI metadata": "/mlpipeline-ui-metadata.json"},
          "image": "jagadeeshj/visualize_html:25-02-2021-17-32-24.356692"}}, "inputs":
          [{"description": "Path of Website log", "name": "board_path", "type": "String"}],
          "name": "WebApplication Viz", "outputs": [{"name": "MLPipeline UI metadata",
          "type": "UI metadata"}, {"description": "Path for the output", "name": "outputs",
          "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "fdd4fd52d2770d6dd9b2a18fc3981755734ed4828408c6b0656f4a4fcc0e1078", "url":
          "visualize_html/bert/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"board_path":
          "{{inputs.parameters.train-pytorch-bert-WebS3Path}}"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
